name: Exec commands on Pods

on:
  workflow_dispatch:
    inputs:
      command:
        type: text
        description: command
        required: true
        default: "help"
      deployment:
        type: text
        description: "deployment name"
        required: true
        options:
          - "three-backend-celery"
          - "three-backend-insurance"
        default: "three-backend-insurance"

permissions:
  contents: read
  checks: write

jobs:
  exec:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    env:
      RESOURCE_GROUP: "SOC-ProdNC-RG"
      CLUSTER_NAME: "S0C-Prod-K8s"
      NAMESPACE: "socotra"
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      - name: Prepare Agent
        run: |
          #install kubectl and kubelogin
          sudo az aks install-cli

          #Prepare KubeConfig
          az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --overwrite-existing

          #Use Kubelogin for authentication
          kubelogin convert-kubeconfig -l azurecli

      - name: Exec command on Pod
        run: |
          kubectl exec -ti deployment/${{ github.event.input.deployment }} -n ${{ env.NAMESPACE }} -- python manage.py ${{ github.event.input.deployment }}

      
