name: Exec commands on Pods

on:
  workflow_dispatch:
    inputs:
      env:
        type: text
        description: command
        required: true
        default: "help"

permissions:
  contents: read
  checks: write

jobs:
  exec:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      - name: exec commands on Pods
        run: |
          az aks get-credentials --resource-group SOC-ProdNC-RG --name S0C-Prod-K8s --overwrite-existing
          kubelogin convert-kubeconfig -l azurecli
          kubectl get namespaces

      
