name: Build the Socotra Repository

on:
  workflow_dispatch:
    inputs:
      env:
        type: environment
        description: Environment
        required: true
        default: Development

permissions:
  contents: read
  checks: write

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.configure-environment.outputs.env }}
    steps:
      - id: configure-environment
        name: Configure environment
        run: |
          environment="${{github.event.inputs.env}}"
          branch="${{github.ref_name}}"
          target="${environment:-$branch}"
          
          if [[ "$target" == "develop" || "$target" == "development" ]]; then
            echo "env=dev" >> $GITHUB_OUTPUT
          elif [[ "$target" == "qa" ]]; then
            echo "env=qa" >> $GITHUB_OUTPUT
          elif [[ "$target" == "stage" || "$target" == "uat" ]]; then
            echo "env=stage" >> $GITHUB_OUTPUT
          elif [[ "$target" == "production" ]]; then
            echo "env=production" >> $GITHUB_OUTPUT
          else
            echo "Branch is not valid" >&2
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    needs: configure
    env:  
      repo_dir: "socotra-source-code-build" 
    environment: ${{ needs.configure.outputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.repo_dir }}
          fetch-depth: 0
      - name: configure git
        working-directory: ${{ env.repo_dir }}
        run: |
          # setup the username and email.
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>" 
      - name: Build Socotra
        run: bash ${{ env.repo_dir }}/.github/generate_builds.sh
        env:
          REPO_DIR: ${{ env.repo_dir }}
          
        
      
