name: Restart ACA Services

on:
  workflow_dispatch:
    inputs:
      env:
        type: environment
        description: Environment
        required: true
        default: development
      app:
        type: choice
        description: Application
        required: true
        options:
          - Web
          - Celery
          - Celery-Beat
          - Flower
          - LOB
          - Stripe

jobs:
  configure:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    outputs:
      RESOURCE_NAME: ${{ steps.configure-environment.outputs.RESOURCE_NAME }}
      RESOURCE_GROUP: ${{ steps.configure-environment.outputs.RESOURCE_GROUP }}
    steps:
      - name: Define Resource Map
        id: configure-environment
        run: |
          RESOURCE_NAMES_MAP='{
            "Web": "api",
            "Celery": "celery",
            "Celery-Beat": "celery-beat",
            "Flower": "celery-flower",
            "LOB": "lob",
            "Stripe": "stripe"
          }'

          ENVIROMENTS_MAP='{
            "development": "dev",
            "qa": "qa",
            "training": "training",
            "production": "prod"
          }'
          
          ENVIRONMENT="$(echo $ENVIRONMENTS_MAP | jq -r .[${{ github.event.inputs.env }}])"
          APPLICATION="$(echo $RESOURCE_NAMES_MAP | jq -r .[${{ github.event.inputs.app }}])"
          
          RESOURCE_NAME="$ENVIRONMENT-$APPLICATION"
          RESOURCE_GROUP="agent-portal-$ENVIRONMENT-container-apps"
          
          echo "RESOURCE_NAME=$RESOURCE_NAME" >> $GITHUB_OUTPUT
          echo "RESOURCE_GROUP=$RESOURCE_GROUP" >> $GITHUB_OUTPUT
          echo "Selected resource: $RESOURCE_NAME; RG: $RESOURCE_GROUP"
