name: Test Action

on: 
  workflow_dispatch:
    inputs:
      env:
        type: environment
        description: Environment
        default: development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        name: test
        run: |
          echo "This is a test"
    
          
